### ISSUE TITLE
initial POC

### ISSUE THREAD

**Issue by avdd** [avdd/loco#4]
Create initial proof of concept

- [x] redirect / to /home
- [x] serve skeleton html with inline css/js
- [x] serve Home component
- [x] serve bundle css
- [x] serve app js
- [x] success: selenium can see loaded home component

plan at https://github.com/avdd/loco/issues/4#issuecomment-1374654533

**Comment by avdd** [comment]
status: figuring my way around selenium and its interaction with lazy loaded JS

**Comment by avdd** [comment]
will most likely proceed with ES modules as they can run without modification in the browser and node, and we can deal with js loading performance later.

also, what is a good approach to starting and stopping the server and browser processes per test?  starting firefox is slooow

**Comment by avdd** [comment]
OK here is the plan.

- start server with environment `SELENIUM_TEST=1`
- server sets cookie `selenium-test=1`
- skeleton JS check cookie
- if cookie missing, call `StartLoading()`
- selenium test setup calls `StartLoading()`
- call `LoadingProgress()` for each step below
- `StartLoading()` adds `<script>` reference to `app.js`
- `app.js` fetches `app.css` and adds `<style>`
- `app.js` calls `App.init()`
- `App.init` fetches `screen/home`
- call `initComponents()`
- call `FinishLoading()`
- selenium test checks for presence of Home

further tweaks/refactoring:

- start server and browser once only, and clean up between tests
- separate the bootstrapping test above from subsequent TestCases
- use overlay with high `z-index` for loading message, reveal with fade

**TODO**:

- refactor JS components
- JS testing support using node
- generate JS component registry boilerplate
- separate python unit/integration/functional testing
- create TODOs for POC next steps

**Comment by avdd** [comment]
> also, what is a good approach to starting and stopping the server and browser processes per test? starting firefox is slooow

done: use class-level setup

**Comment by avdd** [comment]
Calling this done.  Further work to be chunked into issues
